apiVersion: v1
kind: Service
metadata:
  name: cadvisor-nodeport-svc
  namespace: kube-system
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '9090'
spec:
  type: NodePort
  selector:
    name: cadvisor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30003